SELECT 
    YEAR(o.SALES_DATE) AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    COUNT(DISTINCT o.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM 
    ONLINE_SALE o
INNER JOIN 
    USER_INFO u ON o.USER_ID = u.USER_ID AND YEAR(u.JOINED) = 2021
GROUP BY 
    YEAR(o.SALES_DATE),
    MONTH(o.SALES_DATE)
ORDER BY 
    YEAR(o.SALES_DATE), MONTH(o.SALES_DATE);
