## FBA_FSD_HW1
## Programmers 문제 풀이

# https://school.programmers.co.kr/learn/courses/30/lessons/144854?language=mysql

# Problem 1. 조건에 맞는 도서와 저자 리스트 출력하기
SELECT BOOK_ID,AUTHOR_NAME,
DATE_FORMAT(PUBLISHED_DATE,"%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK
INNER JOIN AUTHOR
ON book.author_id = author.author_id
WHERE category = '경제'
ORDER BY published_date

## TO_CHAR()로 해보니 오류가 난다
## DATE_FORMAT()을 사용하니 맞게 됨

# DATE_FORMAT() 사용법 참조
https://velog.io/@donghoim/MySQL-DATETIME-%EC%9B%90%ED%95%98%EB%8A%94-%EC%9C%A0%ED%98%95%EC%9C%BC%EB%A1%9C-%EB%B3%80%EA%B2%BD-YYMMDD



##2
(오답) - INNER JOIN 사용하려고 함
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME 
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.NAME IN ANIMAL_OUTS 
AND ANIMAL_INS.NAME NOT IN ANIMAL_INS

(정답)
# 유실된 것 - A에는 있지만 B에는 없는 데이터를 찾는 것 : LEFT JOIN
# 하고 A IS NOT NULL, B IS NULL 하면 A-B 차집합 부분을 찾을 수 있음
SELECT A.ANIMAL_ID, A.NAME 
FROM ANIMAL_OUTS AS A           # 긴 col.name을 AS로 축소 가능
LEFT JOIN ANIMAL_INS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.NAME IS NOT NULL 
AND B.NAME IS NULL
ORDER BY A.ANIMAL_ID


#3
SELECT A.ANIMAL_ID, A.NAME 
FROM ANIMAL_OUTS AS A
LEFT JOIN ANIMAL_INS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME < B.DATETIME  # 보호 시작일보다 입양일이 더 빠름 (잘못된 경우 조회)
ORDER BY B.DATETIME


#4
(오답)
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A
LEFT JOIN ANIMAL_OUTS AS B
ON A.NAME = B.NAME             # 잘못된 부분
WHERE A.NAME IS NOT NULL
AND B.NAME IS NULL
ORDER BY DATETIME 
LIMIT 3


(정답)
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A
LEFT JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID  # NAME 대신 ANIMAL_ID를 사용하니 맞게 됨
WHERE A.NAME IS NOT NULL
AND B.NAME IS NULL
ORDER BY DATETIME 
LIMIT 3


#5 - 보호소에서 중성화한 동물
# 설명
# 들어왔을 때 중성화 X : Intact라는 단어가 SEX_UPON_INTAKE 열에 있어야 함
  나갈 때 중성화 O : Spayed or Neutered라는 단어가 SEX_UPON_OUTCOME 열에 있어야 함
  Spayed, Neutered 둘 다 가능하므로 괄호로 구문을 묶어줌
SELECT A.ANIMAL_ID,A.ANIMAL_TYPE,A.NAME 
FROM ANIMAL_INS AS A
INNER JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE '%Intact%'
AND (SEX_UPON_OUTCOME LIKE '%Spayed%'
     OR SEX_UPON_OUTCOME LIKE '%Neutered%')


#6 - 상품 별 오프라인 매출 구하기
# 설명
# 상품코드 별 매출액 : 판매가 * 판매량
# 판매가(price)는 같은 PRODUCT_CODE에 대해 동일하므로 그대로 사용,
# 판매량은 전부 더해서 사용(SUM(SALES_AMOUNT))
SELECT PRODUCT_CODE, price*SUM(SALES_AMOUNT) AS SALES
FROM PRODUCT AS A
INNER JOIN OFFLINE_SALE AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC ,PRODUCT_CODE ASC


# Problem 2. 그룹별 조건에 맞는 식당 목록 출력하기
(오답)
SELECT MEMBER_NAME,REVIEW_TEXT,
DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS A
INNER JOIN REST_REVIEW AS B
ON A.MEMBER_ID = B.MEMBER_ID
GROUP BY MEMBER_NAME
WHERE MEMBER_NAME IN  
(SELECT MEMBER_NAME
FROM MEMBER_PROFILE INNER JOIN REST_REVIEW
ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
GROUP BY MEMBER_NAME)